
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pilotjones
 */
import java.util.Random;
public class hiraganaUI extends javax.swing.JFrame {
    private static Hira h = new Hira();
    private static Random random = new Random();
    private  int nA=  random.nextInt(1, 4);//random number of bottom that show corrat answer
    private  String t1;//empty String go to custom code bottom1 to see assing value
    private  String t2;//empty String go to custom code bottom1 to see assing value
    private String t3;//empty String  go to custom code bottom1 to see assing value
    private  String a;//empty String go to custom code bottom1 to see assing value

    /**
     * Creates new form hiraganaUI
     */
    public hiraganaUI() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("assets/jpnFlag"
                + ".png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mainSakura = new javax.swing.JLabel();
        bgFade = new javax.swing.JLabel();
        bgColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nihon-Go");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainPanel.setLayout(null);

        Hira gan = new Hira();
        String q = gan.ganQuestion();
        jLabel1.setFont(new java.awt.Font("Yu Mincho", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(q);
        jLabel1.setToolTipText("");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(580, 200, 70, 90);

        backLabel.setFont(new java.awt.Font("Manga Temple", 1, 18)); // NOI18N
        backLabel.setForeground(new java.awt.Color(46, 3, 37));
        backLabel.setText("BACK");
        mainPanel.add(backLabel);
        backLabel.setBounds(610, 600, 70, 40);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        mainPanel.add(backButton);
        backButton.setBounds(540, 600, 200, 50);

        t1 = h.getText(); // get rondom romanji form hari calss
        t2 = h.getText2();// get rondom romanji form hari calss
        t3 = h.getText3();// get rondom romanji form hari calss
        a=h.getAnswer(); // get correct romanji form hari calss
        int b1 = 1; // numbur refer button 1
        int b2 = 2;// numbur refar button 2
        int b3 = 3;// numbur refar button 3
        // chcek if this bottom goning to show correct answer or not
        // this logic chcek have in all the button
        if(b1==nA){
            jButton1.setText(a);
        }else{
            jButton1.setText(t1);
        }
        mainPanel.add(jButton1);
        jButton1.setBounds(260, 390, 100, 100);

        if(b2==nA){
            jButton2.setText(a);
        }else{
            jButton2.setText(t2);
        }
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mainPanel.add(jButton2);
        jButton2.setBounds(570, 390, 100, 100);

        if(b3==nA){
            jButton3.setText(a);
        }else{
            jButton3.setText(t3);
        }
        mainPanel.add(jButton3);
        jButton3.setBounds(880, 390, 100, 100);

        mainSakura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mainSakura.png"))); // NOI18N
        mainPanel.add(mainSakura);
        mainSakura.setBounds(0, 0, 1280, 720);

        bgFade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fade.png"))); // NOI18N
        mainPanel.add(bgFade);
        bgFade.setBounds(0, 0, 1280, 720);

        bgColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bgColor.png"))); // NOI18N
        mainPanel.add(bgColor);
        bgColor.setBounds(0, 0, 1280, 720);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_formWindowOpened

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        newGameUI ngui = new newGameUI();

        ngui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hiraganaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hiraganaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hiraganaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hiraganaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public  void run() {
                new hiraganaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel bgColor;
    private javax.swing.JLabel bgFade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainSakura;
    // End of variables declaration//GEN-END:variables
}
